'use server';

/**
 * @fileOverview AI-powered music playlist generator.
 *
 * - generateMusicPlaylist - A function that generates a music playlist based on a selected track.
 * - GenerateMusicPlaylistInput - The input type for the generateMusicPlaylist function.
 * - GenerateMusicPlaylistOutput - The return type for the generateMusicPlaylist function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import wav from 'wav';

const GenerateMusicPlaylistInputSchema = z.object({
  selectedTrack: z.string().describe('The name of the music track selected by the user.'),
});

export type GenerateMusicPlaylistInput = z.infer<typeof GenerateMusicPlaylistInputSchema>;

const GenerateMusicPlaylistOutputSchema = z.object({
  playlist: z.array(
    z.string().describe('A list of music tracks similar to the selected track.')
  ).describe('A playlist of similar music tracks generated by AI.'),
});

export type GenerateMusicPlaylistOutput = z.infer<typeof GenerateMusicPlaylistOutputSchema>;

export async function generateMusicPlaylist(input: GenerateMusicPlaylistInput): Promise<GenerateMusicPlaylistOutput> {
  return generateMusicPlaylistFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateMusicPlaylistPrompt',
  input: {schema: GenerateMusicPlaylistInputSchema},
  output: {schema: GenerateMusicPlaylistOutputSchema},
  prompt: `You are a music expert. Generate a playlist of 5 songs that are similar to the following track: {{{selectedTrack}}}. Only return an array of song names, nothing else.
  `,
});

const generateMusicPlaylistFlow = ai.defineFlow(
  {
    name: 'generateMusicPlaylistFlow',
    inputSchema: GenerateMusicPlaylistInputSchema,
    outputSchema: GenerateMusicPlaylistOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
